services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config